### ISSUE TITLE
maximum number of function calls reached in fmin

### ISSUE THREAD

**Issue by nicolaschotard** [snfactory/cubefit#14] opened 2015-09-21 13:27 UTC
While runing the code during the test production, I've encountered a maximum calls reached in fmin (for many SN, usually in R). Here is an example, and the absolute path to the config.json file used (at CC), where the absoulte paths to the cubes have been added.

/afs/in2p3.fr/group/snovae/snprodJob/00-13/cubefit/SNF20070712-003/SNF-0013-CUBEFIT_Rb-20070712-003_config.json

INFO: cubefit started at 2015-09-17 16:14:42
INFO: parameters: mu_wave=0.07 mu_xy=0.001 refitgal=False
INFO: reading config file
INFO: reading 21 data cubes
INFO: setting up PSF and ADR for all 21 epochs
INFO: guessing sky for all 21 epochs
INFO: fitting galaxy to master ref [18]
INFO:         success: 865 iterations, 898 calls, val=218025.65
INFO: fitting position of non-master refs [17, 19, 20]
Traceback (most recent call last):
  File "/afs/in2p3.fr/group/snovae/snf/cubefit/bin/cubefit", line 45, in <module>
    master_ref=args.master_ref)
  File "/afs/in2p3.fr/group/snovae/snf/cubefit/lib/python2.7/site-packages/cubefit/main.py", line 239, in main
    (yctr[i], xctr[i]), atms[i])
  File "/afs/in2p3.fr/group/snovae/snf/cubefit/lib/python2.7/site-packages/cubefit/fitting.py", line 419, in fit_position_sky
    _check_result_fmin(warnflag)
  File "/afs/in2p3.fr/group/snovae/snf/cubefit/lib/python2.7/site-packages/cubefit/fitting.py", line 32, in _check_result_fmin
    raise RuntimeError("maximum number of function calls reached in fmin")
RuntimeError: maximum number of function calls reached in fmin

**Comment by kbarbary** [comment] 2015-10-18 20:33
Based on Nico's email, only two instances of this error remain after fixing the plan scripts:

```
PTF10ndc/SNF-0013-CUBEFIT2_Bb-10ndc.err:RuntimeError: maximum number of function calls reached in fmin
SNF20070504-017/SNF-0013-CUBEFIT2_Rb-20070504-017.err:RuntimeError: maximum number of function calls reached in fmin
```

Looking into these now.

**Comment by kbarbary** [comment] 2015-10-18 21:33
Side note: the config file for SNF20070504-017 seems to contain only 2 cubes, both of which are references. @nicolaschotard, do you know what's going on there?

**Comment by kbarbary** [comment] 2015-10-18 21:49
`fmin()` is used in the simplest fitting step: fitting the position of each non-master final ref to the master final ref. It is a two parameter fit (x and y position), so we've just been using a simple fitting method. The maximum number of function evaluations in `fmin` seems undocumented, but [looking at the source code](https://github.com/scipy/scipy/blob/v0.16.0/scipy/optimize/optimize.py#L422) the default is `200 * N_params` or in our case `400`. This does seem a bit low.

In PTF10ndc_B, I get
```
INFO fitting position of non-master refs [20]
INFO         success: 188 iterations, 377 calls, val=104035.94
```

In SNF20070504-017, I get
```
INFO fitting position of non-master refs [0]
INFO         success:  51 iterations,  95 calls, val=87529.73
```

so I can't reproduce the problem, but in PTF10ndc the number of function calls (377) is quite close to the limit (400).

We could simply up the limit. However, first I'm going to try moving to using `fmin_l_bfgs_b` as in the other steps. Now that we have the analytic position gradient from #15, it should be easy.

**Comment by kbarbary** [comment] 2015-10-19 01:56
Switched to using `fmin_l_bfgs_b`, should be fixed.

**Closed by kbarbary** 2015-10-19 01:56 UTC

**Comment by nicolaschotard** [comment] 2015-10-19 07:15
Hi Kyle,

It appears we have only one observation for this SN, appart from the two refs, taken in a non-photometric night (http://snf.in2p3.fr/agenda/07125/ <http://snf.in2p3.fr/agenda/07125/>). Since only one of the ref has been taken in photometric condition, we cannot flux calibrate the cubes taken during the two non-photo nights, which is why only the two taken during night 08107 are kept. This SN should thus not be considered in this analysis for now.
